name: town
description: A location-based messaging app for iOS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.1.0
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  timeago: ^3.3.0  # For "time ago" formatting in status messages

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/